# Generated by Django 6.0.3 on 2026-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('office', 'Office')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='Size in m²', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='units_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
