# Generated by Django 6.0.3 on 2026-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_is_available_alter_property_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
