# Generated by Django 4.2 on 2026-05-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maintenance Request', 'verbose_name_plural': 'Maintenance Requests'},
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='created_by',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('appliance', 'Appliance'), ('structural', 'Structural'), ('pest', 'Pest Control'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal staff notes'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='property_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='unit_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Only visible to staff')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
