# Generated by Django 6.0.3 on 2026-05-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_status'),
        ('maintenance', '0002_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='contracts.contract'),
        ),
    ]
